apiVersion: v1
kind: Pod
metadata:
  name: vistle-hub
  labels:
    k8s-app: vistle-hub
spec:
  containers:
  - name: vistle-hub
    image: docker.io/hlrs/vistle
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 0.5
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 1Gi
    env:
    ports:
    - name: ssh
      protocol: TCP
      containerPort: 22
    - name: vistle
      protocol: TCP
      containerPort: 31093
    - name: vistle-data
      protocol: TCP
      containerPort: 31094
    - name: vistle-vnc
      protocol: TCP
      containerPort: 31590
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - hostPath:
      path: /mnt/bwvisu/data
    name: data
