#--------------------------------------------------------------------------------------------------
# Configuration script for use with continuous integration service travis-ci.org
#

notifications:
  email:
    - aumueller@reserv.at

sudo: false
dist: trusty

language: cpp
os:
    - linux
    - osx

env:
    matrix:
        - APP="vistle" BUILD_TYPE="Debug"
        - APP="vistle" BUILD_TYPE="Release"

matrix:
    exclude:
        # FIXME
        - os: osx

addons:
    apt:
        packages:
            - ninja-build
            - libboost-all-dev
            - libglew-dev
            - libxi-dev
            - libxmu-dev
            - freeglut3-dev
            - qttools5-dev
            - qtscript5-dev
            - libqt5scripttools5
            - libqt5svg5-dev
            - libqt5opengl5-dev
            - libqt5webkit5-dev
            - libxerces-c-dev
            - libpng12-dev
            - libopenscenegraph-dev
            - libtbb-dev
            - libmpich-dev
            - mpich
            - libjpeg-dev
            - libsnappy-dev
            - zlib1g-dev
            - libreadline-dev
            - libassimp-dev
            - libboost-atomic-dev
            - libboost-date-time-dev
            - libboost-exception-dev
            - libboost-filesystem-dev
            - libboost-iostreams-dev
            - libboost-locale-dev
            - libboost-log-dev
            - libboost-math-dev
            - libboost-program-options-dev
            - libboost-python-dev
            - libboost-random-dev
            - libboost-serialization-dev
            - libboost-system-dev
            - libboost-thread-dev
            - libboost-timer-dev
            - libboost-tools-dev
            - libboost-dev

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall xerces-c ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall glew ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall giflib ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall libpng ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall libtiff ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall freetype ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall boost ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall python3 ;fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew reinstall qt5 ;fi
    - if [ "$TRAVIS_OS_NAME" = "trusty" ]; then travis_retry apt-get install --no-install-recommends -y libturbojpeg && cd /usr/lib/x86_64-linux-gnu && ln -s libturbojpeg.so.0 libturbojpeg.so; fi

script:

    - mkdir build-${BUILD_TYPE}
    - cd build-${BUILD_TYPE}
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - ninja -j3
